# Generated by Django 5.0.4 on 2024-04-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_product_amount_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
