# Generated by Django 5.0.4 on 2024-04-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
    ]
