# Generated by Django 5.0.4 on 2024-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_customer_address_remove_customer_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(),
        ),
    ]
