# Generated by Django 5.0.4 on 2024-04-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
