# Generated by Django 5.0.4 on 2024-04-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
