# Generated by Django 5.0.4 on 2024-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tel',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
