# Generated by Django 5.0.4 on 2024-04-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_customer_address_customer_post_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
