# Generated by Django 5.0.4 on 2024-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
