# Generated by Django 5.0.4 on 2024-04-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
