# Generated by Django 5.0.4 on 2024-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_category_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_product', to='product_management.category'),
        ),
    ]
