# Generated by Django 5.0.4 on 2024-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
