# Generated by Django 5.0.4 on 2024-04-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
