# Generated by Django 5.0.4 on 2024-04-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
