# Generated by Django 5.0.4 on 2024-04-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0016_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
